### ISSUE TITLE
make laptop weight a strict float number instead of freetext

### ISSUE THREAD

**Issue by zagrodzki** [zagrodzki/labdoo#1]
currently accepts any text and is represented as string in database. Should be valid floats only, represented as a number in the SQL.

**Comment by zagrodzki** [comment]
@Sandeepdharnia

**Comment by Sandeepdharnia** [comment]
num = float(input("Enter the weight: "))

num_is_float = True
if num_is_float:
    print(num)
else:
    print("Please enter a valid number")
