### ISSUE TITLE
Add a quality check checklist to the process slip

### ISSUE THREAD

**Issue by zagrodzki** [zagrodzki/labdoo#43]

**Comment by Ronald65** [comment]
![New Labdoo Process Slip with checklist](https://user-images.githubusercontent.com/46559874/54982416-16adc680-4fab-11e9-87d1-021d6ad951dd.jpg)

**Comment by Ronald65** [comment]
New Labdoo Process Slip contains a checklist area now. On the right hand there is space for the Labdoo Tag Number (sticker)
