### ISSUE TITLE
process slip improvements after the event

### ISSUE THREAD

**Issue by zagrodzki** [zagrodzki/labdoo#46]
* order of the field on the process slip should match the input form order
* remove keyboard layout from the process slip
* date format - update the input forms to DD.MM.YYYY (but store it in the YYYY-MM-DD format)

**Comment by zagrodzki** [comment]
Assigning to Ron for the paper slip changes, then I'll take care of the date input part.

**Comment by Ronald65** [comment]
![New Labdoo Process Slip with checklist](https://user-images.githubusercontent.com/46559874/54982707-a9e6fc00-4fab-11e9-838a-7c5e0ef6788f.jpg)

**Comment by Ronald65** [comment]
Order of the field on the process slip matches now the input order
Keyboard layout removed from process slip

**Comment by Ronald65** [comment]
The date shoud be entered in the script as show on the process slip (if possible). Guess that Task is yours sebastian...thanks.

**Comment by zagrodzki** [comment]
Done.
